// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAPI.Context;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Entities.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CategoriaId")
                        .HasName("Categorias_pkey");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("WebAPI.Entities.Localizacao", b =>
                {
                    b.Property<int>("LocalizacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocalizacaoId"));

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("GoogleMapsUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("LocalizacaoId")
                        .HasName("Localizacao_pkey");

                    b.ToTable("Localizacao", (string)null);
                });

            modelBuilder.Entity("WebAPI.Entities.Loja", b =>
                {
                    b.Property<int>("LojaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LojaId"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("LocalizacaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("LojaId")
                        .HasName("Lojas_pkey");

                    b.HasIndex("LocalizacaoId");

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("WebAPI.Entities.Mensagem", b =>
                {
                    b.Property<int>("MensagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MensagemId"));

                    b.Property<string>("Conteudo")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("integer");

                    b.Property<int>("RemetenteId")
                        .HasColumnType("integer");

                    b.HasKey("MensagemId");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("RemetenteId");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("WebAPI.Entities.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProdutoId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ProdutoId")
                        .HasName("Produtos_pkey");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("WebAPI.Entities.RegistosPreco", b =>
                {
                    b.Property<int>("RegistoPrecoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegistoPrecoId"));

                    b.Property<decimal>("Credibilidade")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LojaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoAcaoId")
                        .HasColumnType("integer");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("integer");

                    b.HasKey("RegistoPrecoId")
                        .HasName("RegistosPrecos_pkey");

                    b.HasIndex("LojaId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("TipoAcaoId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("RegistosPrecos");
                });

            modelBuilder.Entity("WebAPI.Entities.TipoAcao", b =>
                {
                    b.Property<int>("TipoAcaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoAcaoId"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TipoAcaoId")
                        .HasName("TipoAcao_pkey");

                    b.ToTable("TipoAcao", (string)null);
                });

            modelBuilder.Entity("WebAPI.Entities.TipoUtilizador", b =>
                {
                    b.Property<int>("TipoUtilizadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoUtilizadorId"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TipoUtilizadorId")
                        .HasName("TipoUtilizador_pkey");

                    b.ToTable("TipoUtilizador", (string)null);
                });

            modelBuilder.Entity("WebAPI.Entities.Utilizador", b =>
                {
                    b.Property<int>("UtilizadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UtilizadorId"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("GoogleToken")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TipoUtilizadorId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UtilizadorId")
                        .HasName("Utilizadores_pkey");

                    b.HasIndex("TipoUtilizadorId");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("WebAPI.Entities.Loja", b =>
                {
                    b.HasOne("WebAPI.Entities.Localizacao", "Localizacao")
                        .WithMany("Lojas")
                        .HasForeignKey("LocalizacaoId")
                        .HasConstraintName("FK_Lojas_Localizacao");

                    b.Navigation("Localizacao");
                });

            modelBuilder.Entity("WebAPI.Entities.Mensagem", b =>
                {
                    b.HasOne("WebAPI.Entities.Utilizador", "Destinatario")
                        .WithMany()
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Entities.Utilizador", "Remetente")
                        .WithMany()
                        .HasForeignKey("RemetenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destinatario");

                    b.Navigation("Remetente");
                });

            modelBuilder.Entity("WebAPI.Entities.Produto", b =>
                {
                    b.HasOne("WebAPI.Entities.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK_Produtos_Categorias");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("WebAPI.Entities.RegistosPreco", b =>
                {
                    b.HasOne("WebAPI.Entities.Loja", "Loja")
                        .WithMany("RegistosPrecos")
                        .HasForeignKey("LojaId")
                        .IsRequired()
                        .HasConstraintName("FK_RegistosPrecos_Lojas");

                    b.HasOne("WebAPI.Entities.Produto", "Produto")
                        .WithMany("RegistosPrecos")
                        .HasForeignKey("ProdutoId")
                        .IsRequired()
                        .HasConstraintName("FK_RegistosPrecos_Produtos");

                    b.HasOne("WebAPI.Entities.TipoAcao", "TipoAcao")
                        .WithMany("RegistosPrecos")
                        .HasForeignKey("TipoAcaoId")
                        .IsRequired()
                        .HasConstraintName("FK_RegistosPrecos_TipoAcao");

                    b.HasOne("WebAPI.Entities.Utilizador", "Utilizador")
                        .WithMany("RegistosPrecos")
                        .HasForeignKey("UtilizadorId")
                        .IsRequired()
                        .HasConstraintName("FK_RegistosPrecos_Utilizadores");

                    b.Navigation("Loja");

                    b.Navigation("Produto");

                    b.Navigation("TipoAcao");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("WebAPI.Entities.Utilizador", b =>
                {
                    b.HasOne("WebAPI.Entities.TipoUtilizador", "TipoUtilizador")
                        .WithMany("Utilizadores")
                        .HasForeignKey("TipoUtilizadorId")
                        .HasConstraintName("FK_Utilizadores_TipoUtilizador");

                    b.Navigation("TipoUtilizador");
                });

            modelBuilder.Entity("WebAPI.Entities.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("WebAPI.Entities.Localizacao", b =>
                {
                    b.Navigation("Lojas");
                });

            modelBuilder.Entity("WebAPI.Entities.Loja", b =>
                {
                    b.Navigation("RegistosPrecos");
                });

            modelBuilder.Entity("WebAPI.Entities.Produto", b =>
                {
                    b.Navigation("RegistosPrecos");
                });

            modelBuilder.Entity("WebAPI.Entities.TipoAcao", b =>
                {
                    b.Navigation("RegistosPrecos");
                });

            modelBuilder.Entity("WebAPI.Entities.TipoUtilizador", b =>
                {
                    b.Navigation("Utilizadores");
                });

            modelBuilder.Entity("WebAPI.Entities.Utilizador", b =>
                {
                    b.Navigation("RegistosPrecos");
                });
#pragma warning restore 612, 618
        }
    }
}
